name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run unit tests
      run: |
        echo "{}" > './test-local.settings.json'
        python3 -m unittest discover -s tests -p 'test_*.py'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push to Dockerhub
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: REPO_URL:TAG
        file: ./Dockerfile

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
